# PUID
# PGID
# TZ
# TUNNEL_TOKEN

networks:
  servaarr:
    external: true
    name: servaarr
volumes:
  disk1:
    external: true
    name: disk1
  disk2:
    external: true
    name: disk2
  downloads:
    external: true
    name: downloads

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/configs/radarr:/config
      - disk1:/disk1 
      - disk2:/disk2
      - downloads:/downloads
    networks:
      - servaarr
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/configs/sonarr:/config
      - disk1:/disk1 
      - disk2:/disk2
      - downloads:/downloads
    networks:
      - servaarr
    ports:
      - 8989:8989
    restart: unless-stopped

  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/configs/sonarr-anime:/config
      - disk1:/disk1 
      - disk2:/disk2
      - downloads:/downloads
    networks:
      - servaarr
    ports:
      - 8910:8989
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/configs/sabnzbd:/config
      - disk1:/disk1 
      - disk2:/disk2
      - downloads:/downloads
    networks:
      - servaarr
    ports:
      - 8080:8080
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/configs/prowlarr:/config
      - disk1:/disk1 
      - disk2:/disk2
      - downloads:/downloads
    networks:
      - servaarr
    ports:
      - 9696:9696
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /opt/configs/overseerr:/config
      - disk1:/disk1 
      - disk2:/disk2
      - downloads:/downloads
    networks:
      - servaarr
    ports:
      - 5055:5055
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8090
    volumes:
      - /opt/configs/overseerr:/config
      - disk1:/disk1 
      - disk2:/disk2
      - downloads:/downloads
    networks:
      - servaarr
    ports:
      - 8090:8090
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - servaarr
